laravel/framework:
  source:
    type: git
    url: https://github.com/laravel/framework.git
    reference: master
    success_only: true
  install: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
